version: "3"
services:
  db:
    image: postgres:14.2-alpine
    container_name: postgres-14.3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  backend-ruby:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
    volumes:
      - app-storage:/rails/storage
    depends_on:
      - db
    ports:
      - "3000:3000"
  
  angular-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      # If Production map container port 80 (Nginx) to host port 4200
      # - "4200:80"
      # Development 
      - "4200:4200"
    depends_on:
      - backend-ruby

  
volumes:
  postgres_data: {}
  app-storage: {}
